---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: "* * 22 * *"

jobs:
  smoketest:
    name: Smoke test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Run minimal test build
        run: |
          sudo apt-get update
          make build-depends
          make cpio

  lint:
    name: Code syntax
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Install Dependancies
        run: |
          sudo apt-get update
          make build-depends

      - name: Run the lint tools
        run: |
          make shellcheck flake8

  builds:
    needs: smoketest
    name: Perform builds
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch:
          - armhf
          - amd64

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Install Dependancies
        run: |
          sudo apt-get update
          make build-depends

      - name: Build
        run: |
          export CONFIG_DEBIAN_ARCH=${{ matrix.arch }}
          make cpio

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cpio
          path: build/*.cpio


# TODO:
# - build for the same archs that the travis build did
# - deploy the artifacts, like the travis build did
